import type { User } from './data';

export const sampleUsers: User[] = [
    {
        id: 'sample-user-1',
        fullName: 'Alice Johnson',
        email: 'alice@example.com',
        profilePictureUrlId: 'user-1',
        bio: 'Graphic designer and illustrator with a passion for vibrant colors and clean designs. Love to teach and learn!',
        locationCity: 'Austin',
        locationCountry: 'TX',
        skillsOffered: [
            { name: 'Illustration', level: 'Expert' },
            { name: 'Branding', level: 'Intermediate' },
        ],
        skillsSought: [{ name: 'Photography', level: 'Beginner' }],
        trustScore: 92,
        creditsBalance: 15,
        isAdmin: false,
    },
    {
        id: 'sample-user-2',
        fullName: 'Bob Williams',
        email: 'bob@example.com',
        profilePictureUrlId: 'user-2',
        bio: 'Full-stack developer who enjoys building scalable web applications. Eager to swap my coding skills for something creative.',
        locationCity: 'San Francisco',
        locationCountry: 'CA',
        skillsOffered: [
            { name: 'React', level: 'Expert' },
            { name: 'Node.js', level: 'Expert' },
        ],
        skillsSought: [{ name: 'Guitar', level: 'Beginner' }],
        trustScore: 88,
        creditsBalance: 5,
        isAdmin: false,
    },
    {
        id: 'sample-user-3',
        fullName: 'Charlie Brown',
        email: 'charlie@example.com',
        profilePictureUrlId: 'user-3',
        bio: "I'm a painter and digital artist. I love exploring different mediums. Looking to learn how to cook amazing vegan meals!",
        locationCity: 'Brooklyn',
        locationCountry: 'NY',
        skillsOffered: [{ name: 'Oil Painting', level: 'Expert' }],
        skillsSought: [{ name: 'Vegan Cooking', level: 'Beginner' }],
        trustScore: 95,
        creditsBalance: 20,
        isAdmin: false,
    },
    {
        id: 'sample-user-4',
        fullName: 'Diana Prince',
        email: 'diana@example.com',
        profilePictureUrlId: 'user-4',
        bio: 'Professional chef with 10 years of experience in French cuisine. I want to learn how to build my own website.',
        locationCity: 'Paris',
        locationCountry: 'France',
        skillsOffered: [
            { name: 'French Cuisine', level: 'Expert' },
            { name: 'Pastry', level: 'Intermediate' },
        ],
        skillsSought: [{ name: 'Web Development', level: 'Beginner' }],
        trustScore: 98,
        creditsBalance: 12,
        isAdmin: false,
    },
     {
        id: 'sample-user-5',
        fullName: 'Ethan Hunt',
        email: 'ethan@example.com',
        profilePictureUrlId: 'user-5',
        bio: 'Software engineer by day, aspiring musician by night. Can teach you Python, would love to learn piano.',
        locationCity: 'Seattle',
        locationCountry: 'WA',
        skillsOffered: [{ name: 'Python', level: 'Expert' }],
        skillsSought: [{ name: 'Piano', level: 'Beginner' }],
        trustScore: 85,
        creditsBalance: 8,
        isAdmin: false,
    },
    {
        id: 'sample-user-6',
        fullName: 'Fiona Glenanne',
        email: 'fiona@example.com',
        profilePictureUrlId: 'user-6',
        bio: 'Acoustic guitar player and singer. Looking to get better at photography to shoot my own album cover.',
        locationCity: 'Nashville',
        locationCountry: 'TN',
        skillsOffered: [{ name: 'Acoustic Guitar', level: 'Intermediate' }],
        skillsSought: [{ name: 'Portrait Photography', level: 'Intermediate' }],
        trustScore: 91,
        creditsBalance: 14,
        isAdmin: false,
    },
    {
        id: 'sample-user-7',
        fullName: 'Grace Hopper',
        email: 'grace@example.com',
        profilePictureUrlId: 'user-7',
        bio: 'Yoga instructor and mindfulness coach. I believe in a balanced life. Seeking to learn more about sustainable gardening.',
        locationCity: 'Portland',
        locationCountry: 'OR',
        skillsOffered: [
            { name: 'Vinyasa Yoga', level: 'Expert' },
            { name: 'Meditation', level: 'Expert' },
        ],
        skillsSought: [{ name: 'Gardening', level: 'Beginner' }],
        trustScore: 99,
        creditsBalance: 30,
        isAdmin: false,
    },
    {
        id: 'sample-user-8',
        fullName: 'Heidi Turner',
        email: 'heidi@example.com',
        profilePictureUrlId: 'user-8',
        bio: 'I make pottery and ceramics. Each piece tells a story. I would love to learn how to write short stories to go with my art.',
        locationCity: 'Asheville',
        locationCountry: 'NC',
        skillsOffered: [{ name: 'Pottery', level: 'Expert' }],
        skillsSought: [{ name: 'Creative Writing', level: 'Beginner' }],
        trustScore: 94,
        creditsBalance: 18,
        isAdmin: false,
    },
];
